### ISSUE TITLE
Grand Finals Match

### ISSUE THREAD

**Issue by ted537** [smwa/double_elimination#2]
From the README:

> It doesn't currently handle the grand finals match if the loser wins the first match.

Would you be open to a pull request that added support for a grand finals match? Possibly hidden behind an `(...,extended=False)` flag for backwards compatibility?

**Comment by smwa** [comment]
Yeah for sure! I'm unsure if I want to make it a flag or make it the default. The "bracket-reset final" is very common. I'm not terribly worried about backwards compatibility since usage is rather low

**Comment by smwa** [comment]
I've decided to default to adding the bracket reset final match, with a flag to disable it. I've pushed my code to master, and pushed it to pypi. Let me know what you think!
