### ISSUE TITLE
Participant pools that are not powers of 2

### ISSUE THREAD

**Issue by mooretm** [smwa/double_elimination#6]
Hello, after looking through the code, it seems this package does not allow for participant pools that are not a power of 2; am I correct? I really need to be able to run any number of participants (e.g., 5). Is there a way to do this using the code as is, or would it require updating the package? I appreciate any advice!

**Comment by smwa** [comment]
Hello, this does allow for any number of participants. It gives participants a "by" on the first round if the number of participants is not a power of 2

**Comment by mooretm** [comment]
Thank you for the quick reply! And you're absolutely right - I wrote out the code by hand to understand it better and I made a typo. I just installed the package and everything works (apologies for not thinking of that ahead of time).

**Comment by smwa** [comment]
Happy coding!
